version: 2
project_name: vigia

before:
  hooks:
    - make ui

builds:
  - main: ./cmd/vigia
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    ldflags: -s -w -X main.version={{ .Version }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    files: [LICENSE*, README*]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:"]

release:
  github:
    owner: denerFernandes
    name: vigia
  draft: true
